### ISSUE TITLE
Cannot run trained v3 model

### ISSUE THREAD

**Issue by IsraCode** [PWhiddy/PokemonRedExperiments#189]
I face this error:
➜  baselines git:(master) ✗ python3 run_pretrained_interactive.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.28.0
6697     pyboy.pyboy                    WARNING  The emulation speed might not be accurate when speed-target is higher than 5

loading checkpoint
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Traceback (most recent call last):
  File "/Users/???/Programing/Fun/PokemonRedExperiments/baselines/run_pretrained_interactive.py", line 47, in <module>
    model = PPO.load(file_name, env=env, custom_objects={'lr_schedule': 0, 'clip_range': 0})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stable_baselines3/common/base_class.py", line 716, in load
    check_for_correct_spaces(env, data["observation_space"], data["action_space"])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stable_baselines3/common/utils.py", line 229, in check_for_correct_spaces
    raise ValueError(f"Observation spaces do not match: {observation_space} != {env.observation_space}")
ValueError: Observation spaces do not match: Dict('screen': Box(0, 255, (72, 80), uint8)) != Box(0, 255, (3, 128, 40), uint8)
6820     pyboy.pyboy                    INFO     ###########################
6820     pyboy.pyboy                    INFO     # Emulator is turning off #
6820     pyboy.pyboy                    INFO     ###########################

**Comment by IsraCode** [comment]
fixed it.
since i guess more people will face it, the fix i did:

(the diffs:)

from red_gym_env_v3_minimal import PokeRedEnv
...
def make_env(rank, seed=0):
    def _init():
        env = PokeRedEnv('../PokemonRed.gb', '../has_pokedex_nballs.state')
        env.reset(seed=(seed + rank))
        return env
    set_random_seed(seed)
    return _init
 ...
  env = make_env(0)() 
  action = 6

**Comment by IsraCode** [comment]
oh sh!t

**Comment by IsraCode** [comment]
> Glad you were able to get it working! I should note, the v3 script was an experiment to cut out a bunch of observations and rewards, but it did not get nearly as far as the other versions. the best / latest version in this repo is in the v2 folder at the top level.

you mean, v2/baseline_fast_v2.py is the best one, and baseline/baseline_fast_v2.py in not the best one?
