### ISSUE TITLE
ArrayMemoryError

### ISSUE THREAD

**Issue by avatar00000** [PWhiddy/PokemonRedExperiments#6]
```
Traceback (most recent call last):
  File "C:\Users\x\Desktop\PokemonRedExperiments\baselines\run_pretrained_interactive.py", line 50, in <module>
    model.rollout_buffer.reset()
  File "C:\Python311\Lib\site-packages\stable_baselines3\common\buffers.py", line 364, in reset
    self.observations = np.zeros((self.buffer_size, self.n_envs, *self.obs_shape), dtype=np.float32)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 960. GiB for an array with shape (16777216, 1, 3, 128, 40) and data type float32
```

Windows 11, Python 3.11.5.

**Comment by jatoran** [comment]
Getting this same error

Using Windows 10
Using python venv to wrap the environment

```
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Reinforcement Learning Pokemon\env\PokemonRedExperiments-master\baselines\run_pretrained_interactive.py", line 50, in <module>
    model.rollout_buffer.reset()
  File "C:\Users\x\Desktop\Reinforcement Learning Pokemon\env\Lib\site-packages\stable_baselines3\common\buffers.py", line 364, in reset
    self.observations = np.zeros((self.buffer_size, self.n_envs, *self.obs_shape), dtype=np.float32)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 960. GiB for an array with shape (16777216, 1, 3, 128, 40) and data type float32
```

**Comment by ccaterianoy** [comment]
Same issue on Windows 11 conda enviroment
![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/33458569/8c62d3cb-c206-4903-8a35-16c2bd04c9ea)

**Comment by retrokiller543** [comment]
Also the same running in Fedora linux and using a venv enviroment. 

```
Traceback (most recent call last):
  File "/home/tosic-killer/pokemon-ai/baselines/run_pretrained_interactive.py", line 50, in <module>
    model.rollout_buffer.reset()
  File "/home/tosic-killer/pokemon-ai/pokemon_ai/lib64/python3.11/site-packages/stable_baselines3/common/buffers.py", line 364, in reset
    self.observations = np.zeros((self.buffer_size, self.n_envs, *self.obs_shape), dtype=np.float32)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 960. GiB for an array with shape (16777216, 1, 3, 128, 40) and data type float32
```

**Comment by PWhiddy** [comment]
Thanks for reporting this! Running pretrained should only use a very small amount of memory. I'll try testing this on a clean environment and see if I can reproduce.

**Comment by PWhiddy** [comment]
Should be fixed now!

**Comment by jatoran** [comment]
Yep that did it!  I did have to install ffmpeg as well after that, but now it's all good

**Comment by brav3lung** [comment]
I was having the same problem on both windows and ubuntu, but was able to get around this by changing the value of ep_length in run_pretrained_interactive.py fwiw. 

I'll try reinstalling now that it's been fixed.
