### ISSUE TITLE
Issues running on Ubuntu LXC - What am I doing wrong...

### ISSUE THREAD

**Issue by trentbraidner** [PWhiddy/PokemonRedExperiments#67]
LXC Container: Ubuntu 22.04
vCores: 24
Ram: 128GB
GPU: GTX 1080ti
Access via SSH

I followed all the instructions and (i hope) have done it correctly.

When running ```run_baseline_parallel.py``` I'm getting the following error
Running the single thread baseline ```run_baseline.py``` seems to work though.

Is this an issue due to the errors from pyboy about the emulation_speed?
or is this an NNPACK issue due to my CPU not having AVX2?

```
root@pokeAI:~/PokemonRedExperiments/baselines# python3 run_baseline_parallel.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.28.0
5387     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5708     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5794     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5658     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5774     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5739     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5895     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5812     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
5929     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6050     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6084     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6068     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6120     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6191     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6302     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6491     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6475     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6555     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6491     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6685     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6770     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6737     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6824     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
6958     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
Using cuda device
Wrapping the env in a VecTransposeImage.
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
step:     31 event:  0.00 level:  0.00 heal:  0.00 op_lvl:  0.00 dead: -0.00 badge:  0.00 explore:  0.03 sum:  0.03corrupted size vs. prev_size
step:     32 event:  0.00 level:  0.00 heal:  0.00 op_lvl:  0.00 dead: -0.00 badge:  0.00 explore:  0.05 sum:  0.05Traceback (most recent call last):
  File "/root/PokemonRedExperiments/baselines/run_baseline_parallel.py", line 65, in <module>
    model.learn(total_timesteps=(ep_length)*num_cpu*1000, callback=checkpoint_callback)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    return super().learn(
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 259, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 197, in step
    return self.step_wait()
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 95, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 130, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 130, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
step:     32 event:  0.00 level:  0.00 heal:  0.00 op_lvl:  0.00 dead: -0.00 badge:  0.00 explore:  0.03 sum:  0.03    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

```

**Comment by PWhiddy** [comment]
Hi! It's not a pyboy issue, and I think the NNPACK message is also a warning. 
Curious, if you reduce the `num_cpu` variable in the script to 24 do you still run into this error?

**Comment by trentbraidner** [comment]
> Hi! It's not a pyboy issue, and I think the NNPACK message is also a warning. Curious, if you reduce the `num_cpu` variable in the script to 24 do you still run into this error?

This was actually running with `24` for `num_cpu` already, I have also attempted to run with `12`
First step after it failed with `48` `num_cpu`

**Comment by PWhiddy** [comment]
Curious!

Does running a simple multiprocessing test in your environment like this:

```python
import multiprocessing

def square(n):
    return n * n

if __name__ == "__main__":
    numbers = list(range(32))
    pool = multiprocessing.Pool()
    squares = pool.map(square, numbers)
    pool.close()
    pool.join()
    print(f"Squares: {squares}")
```

work fine?

**Comment by trentbraidner** [comment]
that one works fine
<img width="625" alt="image" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/17211252/9a40f795-2c0c-4733-a74c-4daf7bb09bbf">

`1024`
<img width="1155" alt="image" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/17211252/3145aa8c-301e-4980-b5ea-18eb25d5e415">

**Comment by trentbraidner** [comment]
```root@pokeAI:~/PokemonRedExperiments/baselines# python run_baseline_parallel.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.28.0
4037     pyboy.plugins.window_headless  WARNING  This window type does not support frame-limiting. `pyboy.set_emulation_speed(...)` will have no effect, as it's always running at full speed.
Using cuda device
Wrapping the env in a VecTransposeImage.
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
step:     97 event:  0.00 level:  0.00 heal:  0.00 op_lvl:  0.00 dead: -0.00 badge:  0.00 explore:  0.06 sum:  0.06corrupted size vs. prev_size
Traceback (most recent call last):
  File "/root/PokemonRedExperiments/baselines/run_baseline_parallel.py", line 65, in <module>
    model.learn(total_timesteps=(ep_length)*num_cpu*1000, callback=checkpoint_callback)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    return super().learn(
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 259, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 197, in step
    return self.step_wait()
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 95, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 130, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 130, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

Running with `num_cpu` = 1 appears to allow at least 97 steps vs all other amounts of `num_cpu` seem to have the error at 33

**Comment by PWhiddy** [comment]
I also just noticed the "corrupted size vs. prev_size" message. I wonder if that is any clue.
You're using a recent version of python right? 
And you say you're running this in an LXC Container? I wouldn't expect that to cause an issue, but I haven't tested it myself.
Is there anything else unusual about this system?

**Comment by trentbraidner** [comment]
Im running python 3.10.12.
Nothing unusual I can note about the system. LXC Container running Ubuntu 22.04 on a proxmox host.
I'll rebuild this in a traditional VM and see if that changes anything.

Still not entirely sure if this is a processor thing (AVX2 missing) or an environment thing but hopefully a VM will sort that out.

**Comment by trentbraidner** [comment]
@PWhiddy it seems that running this in a clean VM rather than an LXC lets this run.
Appreciate the help.

Will look further into LXC issue and report back if i find anything at a later stage

**Comment by PWhiddy** [comment]
Glad you were able to figure out a way to make it work! Strange that LXC would cause an issue, I have run these experiments in docker containers in the past.
