### ISSUE TITLE
Crashes with IndexError Out of Bounds

### ISSUE THREAD

**Issue by 0xGingi** [PWhiddy/PokemonRedExperiments#9]
Crashes after ~40min - 1 hour

File "/home/gingi/kick/PokemonRedExperiments/baselines/run_pretrained_interactive.py", line 70, in <module>
    env.render()
  File "/home/gingi/kick/PokemonRedExperiments/baselines/red_gym_env.py", line 165, in render
    self.create_exploration_memory(), 
  File "/home/gingi/kick/PokemonRedExperiments/baselines/red_gym_env.py", line 314, in create_exploration_memory
    make_reward_channel(explore)
  File "/home/gingi/kick/PokemonRedExperiments/baselines/red_gym_env.py", line 304, in make_reward_channel
    memory[:col, row] = 255
IndexError: index 40 is out of bounds for axis 1 with size 40
start.sh: line 3: 845058 Segmentation fault      (core dumped) python run_pretrained_interactive.py

**Comment by Kylogias** [comment]
Can confirm. The error I got is below and the AI was somewhere in Mount Moon when it crashed
```
step:  33181 event: 14.00 level: 29.00 heal:  8.64 op_lvl:  1.80 dead: -0.50 badge:  2.00 explore: 32.00 sum: 86.95Traceback (most recent call last):
  File "/home/kylogias/Desktop/Programming/gitrepos/PokemonRedExperiments/baselines/run_pretrained_interactive.py", line 70, in <module>
    env.render()
  File "/home/kylogias/Desktop/Programming/gitrepos/PokemonRedExperiments/baselines/red_gym_env.py", line 165, in render
    self.create_exploration_memory(), 
  File "/home/kylogias/Desktop/Programming/gitrepos/PokemonRedExperiments/baselines/red_gym_env.py", line 314, in create_exploration_memory
    make_reward_channel(explore)
  File "/home/kylogias/Desktop/Programming/gitrepos/PokemonRedExperiments/baselines/red_gym_env.py", line 304, in make_reward_channel
    memory[:col, row] = 255
IndexError: index 40 is out of bounds for axis 1 with size 40
```

**Comment by PWhiddy** [comment]
Hey thanks for reporting this! By default the maximum steps is 32K (2^16). For now the workaround I have is that you can adjust the `ep_length` parameter in the script. For example `2**17` will double it to 64K. This will also use more memory however.
